FROM python:3.12-slim

WORKDIR /app

COPY deploy/requirements-ui.txt .

RUN pip install --no-cache-dir -r requirements-ui.txt

COPY . .

EXPOSE 8501

CMD ["streamlit", "run", "deploy/ui.py", "--server.address=0.0.0.0"]