FROM python:3.12-slim

WORKDIR /app

COPY deployment/requirements.backend.txt .
RUN pip install --no-cache-dir -r requirements.backend.txt

COPY deployment/api.py .

# copy trained models into container
COPY models ./models

EXPOSE 8000

CMD ["uvicorn", "api:app", "--host", "0.0.0.0", "--port", "8000"]
