services:
  mongo:
    image: mongo:7
    container_name: mongo
    restart: always
    volumes:
      - mongo_data:/data/db
    networks:
      - app_network


  server:
    build: ./server
    container_name: server
    working_dir: /app
    command: sh -c "npm install && npm run start"
    volumes:
      - ./server:/app
    ports:
      - "5000:3000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/appdb
    depends_on:
      - mongo
    networks:
      - app_network

  client:
    build: ./client
    container_name: client
    restart: unless-stopped
    ports:
      - "3000:80"
    depends_on:
      - server

volumes:
  mongo_data:

networks:
  app_network:
    driver: bridge
